---

version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: tmaier/docker-compose:17.03
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          apk add --no-cache bash build-base git py-pip python python-dev
          pip install pre-commit
      - restore_cache:
          keys:
            - v1-data-tracking-{{ checksum ".pre-commit-config.yaml" }}
      - run: |
          pre-commit install
          pre-commit run --all-files
      - save_cache:
          key: v1-data-tracking-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.pre-commit
      - run: ./build.sh
      - run: ./tests/test.sh
